export const EnglishWordCloud =
  `windows nice close you too being better now later how base not said heat play cat state cat start sort nice love set peace horse bed head node code learn fun make help work play call soon hold land body down farm size keep wide high area mean grow dark hour rock song turn mark gate line land tool wood roll term main born care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule care form food seem well name view road rule`.split(
    " "
  );

export const AmharicWordCloud =
  `አባት መርካቶ ቤት ሰዎች ሰላሳ መፅሃፍ ስልክ አንበሳ ሄደ ወንድም ወደ ቲክቶክ አረንጓዴ ብር እግዚያብሔር እስራስ ድምጽ እናት አሮጌ ቃላት መጀመሪያ ስሜት ስድብ ሞት እኛ እግር ቆንጆ ሰላም በኋላ ፈረስ አልጋ ትምህርት ስራ ሰውነት እርሻ ከፍተኛ ሰፊ ደውል ቦታ ድንጋይ ሰዐት እድገት ዘፈን ጨለማ እንጨት ሰልፍ ስም ውልደት`.split(
    " "
  );
